const CONSTANTS = {
    PORT:4040,
    MONGODB_URL:"mongodb+srv://taswoorhossein72:treeproject@cluster0.g7xas.mongodb.net", 
    DBNAME:"tree" ,
    ACCESS_TOKEN_SECRET:"jdiwkdh23878234yugddsjfsjhgfdsjkfgedjhgfsfsASGJDGDWEUYGWEUFYJS" ,
    REFRESH_TOKEN_SECRET:"saksjasdkhsa3278942384HKDASDJKGSDGKSuiwryweruijcb",
    ACCESS_TOKEN_EXPIRY :"1m" ,
    REFRESH_TOKEN_EXPIRY:"2m"

}


export const {PORT,MONGODB_URL,DBNAME, ACCESS_TOKEN_SECRET ,ACCESS_TOKEN_EXPIRY ,REFRESH_TOKEN_SECRET ,REFRESH_TOKEN_EXPIRY} =CONSTANTS;